/*
 * Company: Blackaddr Audio
 * Effect Name: Analog Delay
 * Description: A warm analog-based delay with multiple filters for different flavours. Boss DM3 inspired.
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#include <cmath>
#include "Aviate/EfxPrint.h"
#include "Aviate/LibBasicFunctions.h"
#include "AnalogDelay.h"

using namespace Aviate;

namespace BlackaddrAudio_AnalogDelay {

void AnalogDelay::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void AnalogDelay::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : delay( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : filter( (paramValue - 0.000000) / (2.000000 - 0.000000) ); break;
    case 3 : mix( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 4 : feedback( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 5 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 6 : longdelay( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float AnalogDelay::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // delay
    case 2 : return ( ((2.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // filter
    case 3 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // mix
    case 4 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // feedback
    case 5 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 6 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // longdelay
    default : return 0.0f;
    }
}

void AnalogDelay::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Delay_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Delay_e][MIDI_CONTROL] == control)) {
        delay(val);
        return;
    }

    if ((m_midiConfig[Filter_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Filter_e][MIDI_CONTROL] == control)) {
        filter(val);
        return;
    }

    if ((m_midiConfig[Mix_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Mix_e][MIDI_CONTROL] == control)) {
        mix(val);
        return;
    }

    if ((m_midiConfig[Feedback_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Feedback_e][MIDI_CONTROL] == control)) {
        feedback(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[LongDelay_e][MIDI_CHANNEL] == channel) && (m_midiConfig[LongDelay_e][MIDI_CONTROL] == control)) {
        longdelay(val);
        return;
    }

}

audio_block_t* AnalogDelay::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = { 0x60, 0xea, 0x2c, 0xcb, 0x8b, 0xf3, 0xb4, 0x39, 0x1b, 0xd4, 0xdf, 0x87, 0x58, 0x81, 0x05, 0x81, 0x4f, 0xc2, 0x28, 0x71, 0xe8, 0x09, 0x42, 0xcf, 0x90, 0x29, 0xdf, 0x01, 0xaa, 0x45, 0xf6, 0x11, 0xd5, 0x97, 0x64, 0x2d, 0xe1, 0xf9, 0xac, 0xb9, 0x4e, 0xe3, 0xd9, 0xdd, 0x00, 0xa8, 0xe7, 0xf8, 0x5b, 0x6b, 0x6d, 0xa6, 0x99, 0xf8, 0x54, 0xff, 0xae, 0xe0, 0x96, 0xcb, 0x3b, 0x66, 0xef, 0x05, 0x50, 0x6c, 0x33, 0x79, 0x10, 0x89, 0x12, 0xe5, 0xe6, 0xba, 0x9f, 0xd5, 0x90, 0xe0, 0xc1, 0x7b, 0xc6, 0x17, 0x32, 0xcc, 0xe3, 0xc1, 0x36, 0x2c, 0x30, 0x16, 0x3f, 0xd1, 0x82, 0xd9, 0xcb, 0x44, 0x01, 0xf9, 0x05, 0xdc, 0x18, 0x36, 0x2e, 0x58, 0x6c, 0x9b, 0xf1, 0x0b, 0xf4, 0x02, 0x69, 0x12, 0xa3, 0x44, 0xa3, 0x14, 0xe6, 0x16, 0xc6, 0xf6, 0x76, 0x02, 0x44, 0x56, 0xc6, 0x16, 0x97, 0x00, 0x47, 0xe9, 0x37, 0x32, 0x53, 0x51, 0xd0, 0x68, 0x2a, 0xa1, 0x8d, 0xee, 0xae, 0x4e, 0xe9, 0xfb, 0xf5, 0x56, 0x2b, 0x76, 0xe5, 0x43, 0xc7, 0xb3, 0xd1, 0x8f, 0x77, 0x10, 0x0a, 0x63, 0x54, 0x51, 0x4c, 0x8b, 0x83, 0x9f, 0xdc, 0x54, 0x08, 0x06, 0xf5, 0x95, 0xf5, 0xa4, 0xe3, 0xde, 0x9f, 0xd9, 0x34, 0xca, 0x4f, 0x19, 0x0e, 0x16, 0xcc, 0xdf, 0xa5, 0x44, 0xef, 0xaf, 0xa7, 0x43, 0x01, 0xf3, 0xce, 0x84, 0x93, 0xab, 0xd8, 0x9b, 0xb1, 0xce, 0x30, 0xa6, 0x72, 0x14, 0x84, 0x11, 0xed, 0xb8, 0xdb, 0x3c, 0xd2, 0xe9, 0x52, 0x9e, 0xc8, 0xf7, 0xe2, 0xb7, 0xa7, 0x89, 0xfa, 0xa8, 0x7d, 0xc9, 0x2c, 0x10, 0x74, 0x05, 0xab, 0x25, 0xd3, 0xdb, 0xcc, 0x45, 0xef, 0x50, 0x56, 0xdc, 0x09, 0x31, 0x18, 0xdb, 0x1b, 0x6a, 0x79, 0xe3, 0x62, 0x5c, 0x9b, 0x09, 0xe5, 0x95, 0xb1, 0x62, 0x5e, 0xdd};
const uint8_t* AnalogDelay::getRblk() { return rblk; }
static constexpr char PROGMEM AnalogDelay_name[] = {0x42, 0x6c, 0x61, 0x63, 0x6b, 0x61, 0x64, 0x64, 0x72, 0x20, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x3a, 0x44, 0x3a, 0x41, 0x6e, 0x61, 0x6c, 0x6f, 0x67, 0x20, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x0};
const char* AnalogDelay::getName() { return AnalogDelay_name; }

}
